#!/bin/bash
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
# }}}
#
# Copyright 2025 Jalil HESSANE
#

#
# This script builds illumos, make SVR4 packages out of it and install them in
# the proto directory. Because of the way that illumos produces it's build,
# it's a bit wiser to install from the IPS repo it creates than it's proto 
# directory, which is actually lacking a few things (mainly some files under
# /etc). Also it's not optimal to directly use the IPS repo because IPS is not
# stupid and want every package's requirement to be satisfied, so it would mean
# packaging every dependency. Also I don't even want a package manager on the
# host, and even for zones IPS is too complicated for my small brain.
#

set -e

. ${XOR_COMPONENTS_DIR}/illumos/conf

# Clone illumos if needed
if [ ! -d "$SRC_DIR/.git" ] && [ -z "$(ls -A "$SRC_DIR" 2>/dev/null)" ]; then
    	echo "Cloning illumos into $SRC_DIR..."
	git clone "$ILLUMOS_REPO" "$SRC_DIR"
else
    	echo "Source directory already populated: $SRC_DIR"
fi

cp ${XOR_ILLUMOS_DIR}/illumos.sh "${SRC_DIR}/illumos.sh"

: '
# Build illumos
cd "$SRC_DIR"

if [ "$INCREMENTAL" = true ]; then
    	echo "Starting illumos incremental build..."
    	time ./usr/src/tools/scripts/nightly -i illumos.sh
else
    	echo "Starting illumos full build..."
    	time ./usr/src/tools/scripts/nightly illumos.sh
fi
'

if [ ! -d "$XOR_ILLUMOS_PACKAGES_DIR" ]; then
  	mkdir -p "$XOR_ILLUMOS_PACKAGES_DIR"
fi

# Make packages
${XOR_ILLUMOS_DIR}/scripts/repo_all -S $CERT

# Install packages into the proto directory
#
# SUNWcs doesn't completly install, so it generate an error, but it's still
# working so that's a future me problem
set +e
# it's quite hacky to pipe yes into pkgadd, but it works, also a future me
# problem 
for pkg in "${XOR_ILLUMOS_PACKAGES_DIR}"/pkgs/*.pkg; do
    	echo "Installing $(basename "$pkg")"
    	yes | pkgadd -R "$XOR_PROTO_DIR" -d "$pkg" all
done

