#!/bin/bash
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
# }}}
#
# Copyright 2025 Jalil HESSANE
#

#
# Illumos configuration. See also illumos.sh
#

export ILLUMOS_REPO="https://github.com/jhessane/illumos-xor.git"
export XOR_ILLUMOS_DIR="${XOR_COMPONENTS_DIR}/illumos"
export SRC_DIR="${XOR_ILLUMOS_DIR}/illumos-xor"
export XOR_ILLUMOS_PACKAGES_DIR="${XOR_PACKAGES_DIR}/illumos"
export INCREMENTAL=false
