#!/bin/bash
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
# }}}
#
# Copyright 2025 Jalil HESSANE
#

#
# This script builds components, you can specify which ones with gmake by
# running this:
# gmake components LIST="tintin haddock tournesol"
# For example, here it will build tintin, haddock and tournesol.
#

set -e
: '
for dir in "$XOR_COMPONENTS_DIR"/*/; do
  if [ -d "$dir" ]; then
    script="$dir/build"
    if [ -x "$script" ]; then
      echo "exec $script"
      (cd "$dir" && ./build)
    else
      echo "no build script in $dir"
    fi
  fi
done
'
if [ "$#" -eq 0 ]; then
    for dir in "$XOR_COMPONENTS_DIR"/*/; do
        if [ -x "$dir/build" ]; then
            (cd "$dir" && ./build)
        else
            echo "no build script in $dir"
        fi
    done
else
    for name in "$@"; do
        dir="$XOR_COMPONENTS_DIR/$name"
        if [ -d "$dir" ]; then
            if [ -x "$dir/build" ]; then
                (cd "$dir" && ./build)
            else
                echo "no build script in $dir"
            fi
        else
            echo "$dir not found"
        fi
    done
fi
