#!/bin/bash
#
# {{{ CDDL HEADER
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
# }}}
#
# Copyright 2025 Jalil HESSANE
#

#
# This script makes self signed certificates used to sign packages
#

set -e

if [ ! -f "$CERT.key" ]; then
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "${CERT}.key" -out "${CERT}.crt" -days 365 \
    -subj "/C=FR/ST=NA/L=LIM/O=XOR/OU=dev/CN=xor-pkg-sign"
fi


